language: node_js
node_js:
  - "stable"
install:
  - npm install -g codecov
script:
  - echo "Running lint:"
  - npm run lint
  - echo "Running unit tests:"
  - npm test
  - codecov
  - echo "Running generator of project"
  - node index.js my-app
  - cd my-app && yarn validate
  - echo "Try to build the app"
  - npm run build
  - echo "Try to run project"
  - npm start
  - echo "Try to build for web"
  - npm run build:web
