language: node_js
node_js:
  - "stable"
script:
  - echo "Running lint:"
  - npm run lint
  - echo "Running unit tests:"
  - npm test
  - echo "Running generator of project"
  - node index.js my-app
  - cd my-app && yarn validate
  - echo "Try to build the app"
  - npm run build
  - echo "Try to build for web"
  - npm run build:web
